export default interface Application {
     username: string,
     name: string,
     email: string,
     id: string,
     supervisorApproval: approval,
     benCoApproval: approval,
     headApproval: approval,
     courseName: string,
     courseType: courseType,
     amount: number,
     adjustedAmount: number,
     appDate: Date,
     courseDate: Date,
     courseLocation: string,
     gradeType: gradeType,
     gradeApproval: approval,
     gradeDescription: string,
     justification: string,
     courseDescription: string,
     urgent: boolean,
     specialApproval: boolean,
     grade: string,
     startFile: {},
     secondFile: {},
     preapprovalDescription?: string,
     missedWorkDesc?: string,
     SToEm?: string,
     EmToS?: string,
     HToEm?: string,
     EmToH?: string,
     HToS?: string,
     SToH?: string,
     BCToEm?: string,
     EmToBC?: string,
     BCToS?: string,
     SToBC?: string,
     BCToH?: string,
     HToBC?: string,
}

export type approval = 'Approved' | 'Pending' | 'Rejected';
export type courseType = 'University Course' | 'Seminar' | 'Certification Prep' | 'Certification' | 'Tech Training' | 'Other';
export type gradeType = 'Letter Grade' | 'Score' | 'Percent Score' | 'Presentation';